language: php

php:
  - 7.1

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --verbose
